baseURL = 'https://lewin.netlify.app/'
languageCode = 'es'
title = 'Lewin.app'
paginate = 5

[params]
comments = false
id = "99734fce-4de1-4c17-b0e7-b96d859d379b"

[menu]
### NAVIGATION BAR ###
[[menu.main]]
  # pre = "üìù"
  name = "Art√≠culos"
  url = "/articles/"
  weight = 10
[[menu.main]]
  # pre = "üìö"
  name = "Notas"
  url = "/notes/"
  weight = 20
[[menu.main]]
  # pre = "üì¶"
  name = "Dise√±os"
  url = "/designs/"
  weight = 30
# [[menu.main]]
#   name = "Datos"
#   url = "/dashboard/"
#   weight = 40

### SOCIAL LINKS ###
[[menu.social]]
  name = "Email"
  url = "mailto:lewinkoon@gmail.com"
  pre = "svg/mail.svg"
[[menu.social]]
  name = "Github"
  url = "https://github.com/lewinkoon"
  pre = "svg/github.svg"
[[menu.social]]
  name = "Rss"
  url = "/index.xml"
  pre = "svg/rss.svg"

[markup]
  [markup.highlight]
  noClasses = false
  lineNos = true
  [markup.goldmark.renderer]
  unsafe = true
  [markup.tableOfContents]
  endLevel = 2
  ordered = false
  startLevel = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]

[build]
  noJSConfigInAssets = true
  useResourceCacheWhen = 'fallback'
  writeStats = false
  command = "hugo"
  publish = "public"
[build.environment]
  HUGO_VERSION = "0.101.0"
